//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.111
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Таблица.
    /// </summary>
    // *** Start programmer edit section *** (Таблица CustomAttributes)

    // *** End programmer edit section *** (Таблица CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблицаE", new string[] {
            "Пособие as \'Пособие\'"})]
    [View("ТаблицаL", new string[] {
            "Пособие as \'Пособие\'"})]
    public class Таблица : IIS.111.Расчет
    {
        
        private int fЗаработок_год;
        
        private int fСрзаработок;
        
        private int fПособие;
        
        // *** Start programmer edit section *** (Таблица CustomMembers)

        // *** End programmer edit section *** (Таблица CustomMembers)

        
        /// <summary>
        /// Заработок_год.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Заработок_год CustomAttributes)

        // *** End programmer edit section *** (Таблица.Заработок_год CustomAttributes)
        public virtual int Заработок_год
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Заработок_год Get start)

                // *** End programmer edit section *** (Таблица.Заработок_год Get start)
                int result = this.fЗаработок_год;
                // *** Start programmer edit section *** (Таблица.Заработок_год Get end)

                // *** End programmer edit section *** (Таблица.Заработок_год Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Заработок_год Set start)

                // *** End programmer edit section *** (Таблица.Заработок_год Set start)
                this.fЗаработок_год = value;
                // *** Start programmer edit section *** (Таблица.Заработок_год Set end)

                // *** End programmer edit section *** (Таблица.Заработок_год Set end)
            }
        }
        
        /// <summary>
        /// Пособие.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Пособие CustomAttributes)

        // *** End programmer edit section *** (Таблица.Пособие CustomAttributes)
        public virtual int Пособие
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Пособие Get start)

                // *** End programmer edit section *** (Таблица.Пособие Get start)
                int result = this.fПособие;
                // *** Start programmer edit section *** (Таблица.Пособие Get end)

                // *** End programmer edit section *** (Таблица.Пособие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Пособие Set start)

                // *** End programmer edit section *** (Таблица.Пособие Set start)
                this.fПособие = value;
                // *** Start programmer edit section *** (Таблица.Пособие Set end)

                // *** End programmer edit section *** (Таблица.Пособие Set end)
            }
        }
        
        /// <summary>
        /// Срзаработок.
        /// </summary>
        // *** Start programmer edit section *** (Таблица.Срзаработок CustomAttributes)

        // *** End programmer edit section *** (Таблица.Срзаработок CustomAttributes)
        public virtual int Срзаработок
        {
            get
            {
                // *** Start programmer edit section *** (Таблица.Срзаработок Get start)

                // *** End programmer edit section *** (Таблица.Срзаработок Get start)
                int result = this.fСрзаработок;
                // *** Start programmer edit section *** (Таблица.Срзаработок Get end)

                // *** End programmer edit section *** (Таблица.Срзаработок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Таблица.Срзаработок Set start)

                // *** End programmer edit section *** (Таблица.Срзаработок Set start)
                this.fСрзаработок = value;
                // *** Start programmer edit section *** (Таблица.Срзаработок Set end)

                // *** End programmer edit section *** (Таблица.Срзаработок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблицаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблицаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблицаE", typeof(IIS.111.Таблица));
                }
            }
            
            /// <summary>
            /// "ТаблицаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблицаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблицаL", typeof(IIS.111.Таблица));
                }
            }
        }
    }
}
